version: "3.9"

services:
  api01: &api
    image: gigi
    hostname: api01
    environment:
      - DATABASE_URL=/data/gigi.db
      - PAYMENT_PROCESSOR_URL=http://payment-processor-default:8080
      - FALLBACK_PAYMENT_PROCESSOR_URL=http://payment-processor-fallback:8080
    volumes:
      - gigi-db:/data
    networks:
      - payment-processor
      - rinha-net
    deploy:
      resources:
        limits:
          cpus: "0.65"
          memory: "167MB"

  api02:
    <<: *api
    hostname: api02

  lb:
    image: nginx:1.27.0-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"
    networks:
      - payment-processor
      - rinha-net
    depends_on:
      - api01
      - api02
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "15MB"

volumes:
  gigi-db:

networks:
  payment-processor:
    external: true
  rinha-net:
    driver: bridge
