version: "3.9"

services:
  api01: &api
    image: gigi
    hostname: api01
    environment:
      - PAYMENT_PROCESSOR_URL=http://payment-processor-default:8080
      - FALLBACK_PAYMENT_PROCESSOR_URL=http://payment-processor-fallback:8080
      - NUM_WORKERS=10
    volumes:
      - gigi-db:/data
    networks:
      - payment-processor
      - rinha-net
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "147MB"

  api02:
    <<: *api
    hostname: api02

  redis:
    image: redis:7.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - payment-processor
      - rinha-net
    volumes:
      - redis_data:/data
    command: >
      redis-server
      --appendonly yes
      --save ""
      --appendfsync everysec
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "30MB"

  lb:
    image: nginx:1.27.0-alpine
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"
    networks:
      - payment-processor
      - rinha-net
    depends_on:
      - api01
      - api02
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "25MB"

volumes:
  gigi-db:
  redis_data:

networks:
  payment-processor:
    external: true
  rinha-net:
    driver: bridge
